name: "✨ Feature request"
description: "Suggest an idea for Cachula"
labels: ["enhancement"]
body:
  - type: textarea
    attributes:
      label: Motivation
      description: Why do you need this feature? What problem does it solve?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed solution
      description: How would you like it to work?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Alternatives
      description: Any alternative solutions or workarounds you’ve considered?
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
